### PR TITLE
Allow users to specify topmost tag for text conversion

### PR DESCRIPTION
**Pull request by AndrewFinlay**
Hi there, 

I put this together as I have a need to convert html content below a specific element in the Dom.

I've taken care to ensure that no default behaviours are changed by this modification. 

Thanks for the hard work so far,

Andrew

### CODE REVIEW

**Comment by AndrewFinlay** [comment]
I've added a fix for the word wrap issues, if you need this one can probably be separated out from the previous content.

**Comment by mlegenhausen** [comment]
Wow thanks for all the work :) Will release the features in the next release.

**Comment by mlegenhausen** [comment]
@AndrewFinlay Does the long word option alter the default behaviour?

**Comment by AndrewFinlay** [comment]
It doesn't, the long lines should be left in place unless a long word split is created.  I've created a new PR with a few tests to show this.

**Comment by mlegenhausen** [comment]
Ok thank you will release the new features with version 2.1.0.

**Pull request merged**
