### PR TITLE
upgrade to htmlparser2

### PR DESCRIPTION
**Pull request by rissem**
Just had to change elem.raw -> elem.data

This addresses https://github.com/werk85/node-html-to-text/issues/44

Happy to make any changes to get this PR accepted. Thanks!

### CODE REVIEW

**Comment by wearhere** [comment]
@rissem can you add the test described in #44 to make sure this change fixes that issue?

**Comment by bradvogel** [comment]
@mlegenhausen would be great to get this merged and released. Huge perf improvement!

**Comment by mlegenhausen** [comment]
@rissem Thanks for your help. This was a long time on my list.

**Comment by mlegenhausen** [comment]
Available in Version 3.0.0.

**Comment by curiousdannii** [comment]
This doesn't seem like semver major... in any case, please update the changelog! :)

**Comment by bradvogel** [comment]
This should probably be a minor update - right?

**Comment by mlegenhausen** [comment]
I expect no breaking changes to the resulting html output. But just in case, cause the unittest coverage is not as good as I wish.

**Pull request merged**
