### PR TITLE
Add support for pre-tags, add options for links

### PR DESCRIPTION
**Pull request by pgrm**
1. I've added support for pre - as that is already raw text it shouldn't be formatted anymore.
2. Additionally there are two options for a-tags (described in the README).
3. I've also had problems with the hr - for some reason in some cases a new line was missing, so I've added one manually. For me it's better there is a new line too much than one missing.

### CODE REVIEW

**Comment by pgrm** [comment]
I've added one more commit where I've managed to fix quite many problems with white spaces

**Comment by mlegenhausen** [comment]
Could you please rebase to the latest changes?

**Comment by pgrm** [comment]
Done

**Comment by mlegenhausen** [comment]
Thanks for your pull request :)

**Pull request merged**
