### PR TITLE
Drop support for Node.js < 4; switch from underscore to lodash

### LINKED ISSUE #13: Change from underscore to lodash

### PR DESCRIPTION
**Pull request by realityking**
Biggish refactor. High level changes:

* Drop support for Node.js < 4
* Add Node 8 to the TravisCI config
* Update all dev-dependencies that require Node 4
* Use native ES5/ES6 methods instead of underscore/underscore.string where possible.
* Use lodash instead of underscore/underscore.string
* lodash's `words` is very different from underscore's. The underscore version is super simple, I just inlined it.
* lodash has no implementation of `repeatAll`. I added a custom implementation to the helpers.

I suggest reviewing commit by commit. Let me know if you'd prefer it if I split this up into multiple pull requests.

Fixes #13

### CODE REVIEW

**Comment by realityking** [comment]
@mlegenhausen Could you check this out? Thanks.

**Comment by mlegenhausen** [comment]
@realityking thanks a lot looks good. Could you resolve the conflicts?

**Comment by realityking** [comment]
@mlegenhausen Done.

Also updated to mocha 5.

**Comment by MariaDima** [comment]
Can someone trigger a release so that we can get the changes?

**Comment by realityking** [comment]
@MariaDima This has already been released on npm, it just wasn't tagged on GitHub.

**Pull request merged**
