### PR TITLE
`format` option support all elements

### PR DESCRIPTION
**Pull request by nswbmw**
#71

### CODE REVIEW

**Comment by KillyMXI** [comment]
I appreciate the effort.

But this is being worked on already as a part of #200, even though I haven't stated it explicitly.

I'm reworking a big chunk of code right now, and the solution for this issue should come out naturally as a side effect.

**Comment by nswbmw** [comment]
Thanks for your great work! Feel free to close this PR after bump new version :]

**Comment by KillyMXI** [comment]
Latest commits now allow to assign any provided format function to any tag.
I will update documentation later, but there are tests available as an example.

There are still few other things to address before new version will be ready for release.

I also see a potential for better inline and block-level tags handling now, but that will change existing behavior too much, so I will leave that for another time.

**Comment by KillyMXI** [comment]
Version 6 is now published, with these changes included.
(Note that custom format functions have to be written differently now.)

**Pull request closed without merging**
